apiVersion: v1
kind: Service
metadata:
  name: clickhouse-service
spec:
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: clickhouse-tcp
  - port: 8123
    targetPort: 8123
    protocol: TCP
    name: clickhouse-http
  selector:
    app: clickhouse
